console.log(true && true)
console.log(false || false)
console.log(!true)
console.log(true && false)
console.log(false || true)
console.log(!false)
console.log(true && !false)
console.log(false || true && false)
console.log(!(true && false))
console.log(!(false || false) && true)
console.log(true || false && !true)
console.log(!(true || false) && false)
console.log(false || !(true && false))
console.log(!(false || true && false))
console.log(true && !(false || true && false))
console.log(!(true && (false || true)) || false)
console.log(false || !(!(true && false) || false))
console.log(!(false && (true || false)) && true)
console.log(!((true || false) && !(false && true)))
console.log(false || !(true && !(false || true && false)))
console.log(!(!true || (false && !(true || false))))
console.log(!(false || !(!(true && false) && (false || true))))
console.log(!((false || true) && !(!(false && true) || !(true || false && true))))
console.log((true && false) || true)
console.log(false || !(!(false || true) && false))
console.log(100 && 40 && 30)
console.log(100 && 40 && 0 && 15)
console.log(100 && 40 && "" && 15)
console.log(100 && 40 && undefined && 15)
console.log(100 && 40 && null && 15)
console.log(undefined && null && NaN && "hello")
console.log(100 || 40 || 30)
console.log(0 || 40 || 30)
console.log(0 || "" || 30)
console.log(0 || "" || undefined || null)
console.log(false || 0 || "" || undefined)
console.log("" || "hello" || 0)
console.log(null || undefined || false || 50)
console.log(false || true || false)
console.log(0 || NaN || "JS")
console.log(undefined || null || 0 || "")
console.log("" || 0 || undefined || null || NaN || "hello")
console.log("" || "7")
console.log("hello" && 100 && 50)
console.log(10 && 20 && 30 && false)
console.log(25 || 0 || "")
console.log(50 && NaN && 100)
console.log(0 || 10 && 20)
console.log(false && 10 || 30)
console.log("" || 0 && 50 || "end")